### PR TITLE
Hihglighted text in search bar is unreadable #11

### PR DESCRIPTION
**Pull request by SmitAkbari26**
image

image

Just make slight difference to visible clearly

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Can we use `#464646` instead to match the highlight in the editor?

**Comment by SmitAkbari26** [comment]
image

here in Message background use #464646??

**Comment by SmitAkbari26** [comment]
Previous

image

image
 
i use #464646 as you mention

**Comment by SmitAkbari26** [comment]
Please check latest commit 54e4370522bce7a24022617f14957742dbc18007

**Comment by fabiospampinato** [comment]
🤔 I think your previous color was better, using the same selection color as used in the editor doesn't quite work here because the background color is different, so the contrast is different. I'd say we should probably either go back to your previous color, or find another color between the ones that are currently used.

**Comment by SmitAkbari26** [comment]
So, i change the color and make PR again? or you try some different colors?

**Comment by SmitAkbari26** [comment]
change color mean my previous color

**Comment by fabiospampinato** [comment]
> So, i change the color and make PR again?

You can just push another commit to this branch so that the PR gets updated.

**Comment by SmitAkbari26** [comment]
image
 with this color right??

**Comment by SmitAkbari26** [comment]
Please check new commit b2a892d6483e320880a207f4eac771da02e86e13

**Comment by fabiospampinato** [comment]
Yes, or another color if you can find a better one, preferably a color that is already used by the theme (the fewer different colors the better, usually).

**Comment by SmitAkbari26** [comment]
I make new commit check latest commit b2a892d6483e320880a207f4eac771da02e86e13

**Comment by SmitAkbari26** [comment]
color #aaaaaa with opacity 50:
image

color #f2f2f2 with opacity 36:
image

color #f2f2f2 with opacity 46:
image

color #666666:
image

color #ffffff40:
image

color #ffffff24:
image


Here you can see that all near to same just slightly different,
This #f2f2f2 and #666666 color is used by your theme many places i just try it with little opacity changes.
If you change color let me know my latest commit is on #aaaaaa50 which i do first.

**Comment by fabiospampinato** [comment]
Let's go with `#666666` 🤔 do you want me to make the change, or are you going to update this PR?

**Comment by SmitAkbari26** [comment]
Ok i update PR with color #666666

**Comment by SmitAkbari26** [comment]
I update PR with #666666

Please check latest commit 2d8b8c04504b096b423e31c43f6682002e4229d6

image

**Comment by SmitAkbari26** [comment]
Please check latest commit 2d8b8c04504b096b423e31c43f6682002e4229d6

**Comment by SmitAkbari26** [comment]
Hello @fabiospampinato

**Comment by fabiospampinato** [comment]
Shipped in v1.7.0, thank you.

I got this warning for the commit you pointed to:

Screen Shot 2023-07-17 at 14 13 27

I ended up just making the change manually as it was quicker, I hope you don't mind.

**Pull request closed without merging**
