### PR TITLE
Saturated buttons #12

### PR DESCRIPTION
**Pull request by SmitAkbari26**
Seriously, gray buttons? Looks as if the buttons are unavailable. Please add the characteristic blue accent colours to the buttons.
image

I change the color of the buttons i make blue which need. 
I used #007acc you used in many places and for hover i used little bit dark of that shade.

Here is output,

image

If need to change let me know

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Can you post more screenshots? I'm interested in seeing what the find widget, the search view, and if you can notifications also, look.

---

Like there seem to be many kinds of buttons in the app, I don't remember which buttons those colors have an effect on.

**Comment by SmitAkbari26** [comment]
image

image

with hover,
image

image

go to top button,
image

**Comment by SmitAkbari26** [comment]
image

image

**Comment by fabiospampinato** [comment]
Alrighty, published as v1.6.4. Thanks!

**Comment by SmitAkbari26** [comment]
Thanks

**Pull request merged**
