### PR TITLE
The HTML <center> tag doesn't appear in red/pink like another tag? #10

### PR DESCRIPTION
**Pull request by SmitAkbari26**

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Have you tested this manually?

Can you keep the changes minimal? It looks like only the following might be relevant:

```
    {
      "name": "Invalid deprecated HTML element",
      "scope": "invalid.deprecated.html",
      "settings": {
        "background": "#AE81FF",
        "foreground": "#F9267299"
      }
    },    
```

**Comment by SmitAkbari26** [comment]
i tested it

**Comment by SmitAkbari26** [comment]
image

**Comment by SmitAkbari26** [comment]
I added color like other HTML elements, but it is a bit dark because it is deprecated.

**Comment by SmitAkbari26** [comment]
As suggested by you, I have made all the required changes . 
Take a look on the latest committed request. 
Please let me know if there are any changes required.

**Comment by SmitAkbari26** [comment]
Hello, @fabiospampinato 
Please check latest commit c11152d587939310876bebce54b5e70cac7318d5 and let know if need to make change on that

**Comment by fabiospampinato** [comment]
Released in v1.6.3. Thank you!

**Comment by SmitAkbari26** [comment]
You're welcome!

**Pull request merged**
